// Aurelia Gleam visual novel script lines by level
// Triggers are calendar-week based (independent of performance)

const aureliagleam = {
  1: [
    { speaker: 'aurelia', text: 'A little gift to help you get started.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 Nudge)' },
    { speaker: 'player', text: 'Whats this?' },
    { speaker: 'aurelia', text: 'A nudge.' },
    { speaker: 'player', text: 'That sounds vague.' },
    { speaker: 'aurelia', text: 'Its simple. If a result doesnt land where you hoped, you may adjust it  slightly.' },
    { speaker: 'player', text: 'Adjust it how?' },
    { speaker: 'aurelia', text: 'By one point. Not enough to rewrite the outcome. Just enough to refine it.' },
    { speaker: 'aurelia', text: 'Talent is important.' },
    { speaker: 'aurelia', text: 'But knowing when to make a small correction? Thats discipline.' },
    { speaker: 'player', text: 'So I shouldnt use it every time?' },
    { speaker: 'aurelia', text: 'Use it when something is almost right.' },
    { speaker: 'aurelia', text: 'Most growth happens in small increments.' },
  ],
  2: [
    { speaker: 'aurelia', text: 'Youve settled into a rhythm.' },
    { speaker: 'player', text: 'I think so.' },
    { speaker: 'aurelia', text: 'Good.' },
    { speaker: 'aurelia', text: 'Youve been close to excellence more than once.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 Nudge)' },
    { speaker: 'player', text: 'Another nudge?' },
    { speaker: 'aurelia', text: 'You understand how to use them now.' },
    { speaker: 'player', text: 'When something is almost right.' },
    { speaker: 'aurelia', text: 'Exactly.' },
    { speaker: 'aurelia', text: 'Perfection isnt dramatic. Its adjusted.' },
  ],
  3: [
    { speaker: 'aurelia', text: 'Mid-semester can feel heavy.' },
    { speaker: 'player', text: 'Thats one word for it.' },
    { speaker: 'aurelia', text: 'Sometimes when something doesnt work' },
    { speaker: 'aurelia', text: 'it isnt wrong.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 D12 Extra Roll)' },
    { speaker: 'player', text: 'An extra roll?' },
    { speaker: 'aurelia', text: 'A second attempt.' },
    { speaker: 'player', text: 'That feels generous.' },
    { speaker: 'aurelia', text: 'Its perspective.' },
    { speaker: 'aurelia', text: 'Not every first draft deserves to be final.' },
  ],
  4: [
    { speaker: 'aurelia', text: 'You move differently now.' },
    { speaker: 'player', text: 'Differently how?' },
    { speaker: 'aurelia', text: 'You dont look like youre asking for permission anymore.' },
    { speaker: 'aurelia', text: 'Thats important.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 d6 Extra Roll)' },
    { speaker: 'player', text: 'Whats this?' },
    { speaker: 'aurelia', text: 'A focused second chance.' },
    { speaker: 'player', text: 'Focused?' },
    { speaker: 'aurelia', text: 'If something doesnt land the way you hoped,' },
    { speaker: 'aurelia', text: 'you may roll again  with precision.' },
    { speaker: 'player', text: 'Why a d6?' },
    { speaker: 'aurelia', text: 'Because refinement is better than randomness.' },
    { speaker: 'aurelia', text: 'You no longer need wide swings.' },
    { speaker: 'aurelia', text: 'You need control.' },
  ],
  5: [
    { speaker: 'aurelia', text: 'The year is nearly complete.' },
    { speaker: 'player', text: 'It feels strange.' },
    { speaker: 'aurelia', text: 'It should.' },
    { speaker: 'aurelia', text: 'You wont need these forever.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 Nudge, 1 d6 Extra Roll)' },
    { speaker: 'player', text: 'More adjustments?' },
    { speaker: 'aurelia', text: 'One refinement.' },
    { speaker: 'aurelia', text: 'One second chance.' },
    { speaker: 'aurelia', text: 'Use them wisely. Or dont.' },
    { speaker: 'aurelia', text: 'Trust the work youve already done.' },
  ],
};

export default aureliagleam;
