// Aurelia Gleam visual novel script lines by level
// Triggers are calendar-week based (independent of performance)

const aureliagleam = {
  1: [
    { speaker: 'aurelia', text: 'Welcome to Shiz Academy.' },
    { speaker: 'aurelia', text: 'Im Aurelia Gleam  Senior Prefect of Performance Studies.' },
    { speaker: 'aurelia', text: 'You may hear many things about Shiz. That its prestigious. That its demanding. That it produces stars.' },
    { speaker: 'aurelia', text: 'All of that is true.' },
    { speaker: 'aurelia', text: 'But more importantly it produces artists.' },
    { speaker: 'aurelia', text: 'Youre going to be simply wonderful here. I can tell.' },
    { speaker: 'aurelia', text: 'As Prefect, Im responsible for helping you settle in and pointing you toward the right doors.' },
    { speaker: 'aurelia', text: 'Lets begin with your dorm room.' },
    { speaker: 'aurelia', text: 'In your room, youll find everything you need to develop as an artist: space to create, space to think, and space to try again.' },
    { speaker: 'aurelia', text: 'On your computer, youll find the most important portals.' },
    { speaker: 'aurelia', text: 'myBubble is Ozs favorite social space  where artists connect, listeners gather, and reputations quietly begin.' },
    { speaker: 'aurelia', text: 'Its where your audience will grow.' },
    { speaker: 'aurelia', text: 'Shizy-Fi is our chart system. Every week, new songs rise and fall there.' },
    { speaker: 'aurelia', text: 'It reflects attention. Not always truth  but attention can open doors.' },
    { speaker: 'aurelia', text: 'Each week, youll create a song.' },
    { speaker: 'aurelia', text: 'Youll choose a genre and a theme.  Some pairings naturally harmonize, while riskier combinations can achieve remarkable results, but only if your performance is truly impeccable.' },
    { speaker: 'aurelia', text: 'Songs are ranked on three things: your voice, your lyrics, and your movement.' },
    { speaker: 'aurelia', text: 'Some weeks theyll align beautifully.' },
    { speaker: 'aurelia', text: 'Other weeks youll learn.' },
    { speaker: 'aurelia', text: 'Both are valuable.' },
    { speaker: 'aurelia', text: 'Earn glims through your performances, then visit the Am-Oz-on portal to purchase items to help you craft your songs' },
    { speaker: 'aurelia', text: 'Take your time. Try things. Surprise yourself.' },
    { speaker: 'aurelia', text: 'Shiz has been waiting for you.' },
  ],
  2: [
    { speaker: 'aurelia', text: 'A little gift to help you get started.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 Nudge)' },
    { speaker: 'player', text: 'Whats this?' },
    { speaker: 'aurelia', text: 'A nudge.' },
    { speaker: 'player', text: 'That sounds vague.' },
    { speaker: 'aurelia', text: 'Its simple. If a result doesnt land where you hoped, you may adjust it  slightly.' },
    { speaker: 'player', text: 'Adjust it how?' },
    { speaker: 'aurelia', text: 'By one point. Not enough to rewrite the outcome. Just enough to refine it.' },
    { speaker: 'aurelia', text: 'Talent is important.' },
    { speaker: 'aurelia', text: 'But knowing when to make a small correction? Thats discipline.' },
    { speaker: 'player', text: 'So I shouldnt use it every time?' },
    { speaker: 'aurelia', text: 'Use it when something is almost right.' },
    { speaker: 'aurelia', text: 'Most growth happens in small increments.' },
  ],
  3: [
    { speaker: 'aurelia', text: 'Mid-semester can feel heavy.' },
    { speaker: 'player', text: 'Thats one word for it.' },
    { speaker: 'aurelia', text: 'When everything starts to feel serious' },
    { speaker: 'aurelia', text: 'sometimes the answer isnt to push harder.' },
    { speaker: 'player', text: 'Then what is it?' },
    { speaker: 'aurelia', text: '(Gift Received: Pink Bubbles Performance Effect)' },
    { speaker: 'player', text: 'Oh whats this?' },
    { speaker: 'aurelia', text: 'A little lift.' },
    { speaker: 'player', text: 'Bubbles?' },
    { speaker: 'aurelia', text: 'Why not?' },
    { speaker: 'aurelia', text: 'Not every performance needs weight.' },
    { speaker: 'aurelia', text: 'Sometimes its perfectly acceptable to let things float.' },
  ],
  4: [
    { speaker: 'aurelia', text: 'You move differently now.' },
    { speaker: 'player', text: 'Differently how?' },
    { speaker: 'aurelia', text: 'You dont look like youre asking for permission anymore.' },
    { speaker: 'aurelia', text: 'Thats important.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 d6 Extra Roll)' },
    { speaker: 'player', text: 'Whats this?' },
    { speaker: 'aurelia', text: 'A focused second chance.' },
    { speaker: 'player', text: 'Focused?' },
    { speaker: 'aurelia', text: 'If something doesnt land the way you hoped,' },
    { speaker: 'aurelia', text: 'you may roll again  with precision.' },
    { speaker: 'player', text: 'Why a d6?' },
    { speaker: 'aurelia', text: 'Because refinement is better than randomness.' },
    { speaker: 'aurelia', text: 'You no longer need wide swings.' },
    { speaker: 'aurelia', text: 'You need control.' },
  ],
  5: [
    { speaker: 'aurelia', text: 'The year is nearly complete.' },
    { speaker: 'player', text: 'It feels strange.' },
    { speaker: 'aurelia', text: 'It should.' },
    { speaker: 'aurelia', text: 'You wont need these forever.' },
    { speaker: 'aurelia', text: '(Gift Received: 1 Nudge, 1 d6 Extra Roll)' },
    { speaker: 'player', text: 'More adjustments?' },
    { speaker: 'aurelia', text: 'One refinement.' },
    { speaker: 'aurelia', text: 'One second chance.' },
    { speaker: 'aurelia', text: 'Use them wisely. Or dont.' },
    { speaker: 'aurelia', text: 'Trust the work youve already done.' },
  ],
};

export default aureliagleam;
