// Griswald visual novel script lines by level
// Structure mirrors luminaO: array per level with dialogue entries
const griswald = {
  1: [
    { speaker:'griswald', text:"Heard your track '{{snap.songName}}'." },
    { speaker:'player', text:"Oh. Hi." },
    { speaker:'griswald', text:"You left the distortion in." },
    { speaker:'player', text:"Was that bad?" },
    { speaker:'griswald', text:"No." },
    { speaker:'griswald', text:"It was honest." },
    { speaker:'player', text:"I wasnt sure if it sounded messy." },
    { speaker:'griswald', text:"Messys fine." },
    { speaker:'griswald', text:"Too polished feels like lying." },
    { speaker:'griswald', text:"If youre going to play in the rain, dont complain about getting wet." },
  ],
  2: [
    { speaker:'griswald', text:"Twenty people listening to something rough around the edges." },
    { speaker:'player', text:"You saw?" },
    { speaker:'griswald', text:"Yeah." },
    { speaker:'griswald', text:"Means they werent looking for perfect." },
    { speaker:'player', text:"It still feels small." },
    { speaker:'griswald', text:"Small rooms make louder echoes." },
    { speaker:'griswald', text:"Your last track '{{snap.songName}}' had a line in the second verse." },
    { speaker:'griswald', text:"You almost rushed past it." },
    { speaker:'player', text:"Which line?" },
    { speaker:'griswald', text:"The one about not wanting to be easy to understand." },
    { speaker:'player', text:"You noticed that?" },
    { speaker:'griswald', text:"Yeah." },
    { speaker:'griswald', text:"(Gift Received: Worn Lyric Notebook)" },
    { speaker:'player', text:"A notebook?" },
    { speaker:'griswald', text:"Mines almost full." },
    { speaker:'griswald', text:"Figured you should have one too." },
    { speaker:'player', text:"What for?" },
    { speaker:'griswald', text:"Write things down before you make them impressive." },
    { speaker:'griswald', text:"The first versions usually heavier." },
    { speaker:'griswald', text:"Dont clean it up too fast." },
  ],
  4: [
    { speaker:'griswald', text:'Top five.' },
    { speaker:'player', text:'I didnt think {{snap.songName}} would chart that high.' },
    { speaker:'griswald', text:'Grunge doesnt always rank in the charts.' },
    { speaker:'griswald', text:'but {{snap.songName}} did.' },
    { speaker:'player', text:'Because it was good?' },
    { speaker:'griswald', text:'Because it was real.' },
    { speaker:'griswald', text:'(Gift Received: Rainfall Stage Lighting)' },
    { speaker:'griswald', text:'Try this next time you perform.' },
    { speaker:'player', text:'Rain effects?' },
    { speaker:'griswald', text:'Yeah.' },
    { speaker:'griswald', text:'Makes everything feel grounded.' },
    { speaker:'griswald', text:'Crowds quiet down when it sounds like weather.' },
  ],
  3: [
    { speaker:'griswald', text:"Can I say something without you taking it wrong?" },
    { speaker:'player', text:"Sure." },
    { speaker:'griswald', text:"Last track felt tense." },
    { speaker:'player', text:"Tense how?" },
    { speaker:'griswald', text:"Like you were aiming for the chart instead of the feeling." },
    { type:'choice', speaker:'player', options:[
      'I wanted it to do well.',
      'I was experimenting.',
      'Maybe I was.'
    ], responses:[
      'Nothing wrong with wanting that. Just dont chase it.',
      'Experimentings good. Dont force it.',
      'At least you noticed.'
    ] },
    { speaker:'griswald', text:"The forest doesnt try to be impressive." },
    { speaker:'griswald', text:"It just is." },
    { speaker:'griswald', text:"Your music is better when you stop trying to win." },
  ],
  5: [
    { speaker:'griswald', text:'Number one.' },
    { speaker:'player', text:'I didnt expect that.' },
    { speaker:'griswald', text:'You shouldve.' },
    { speaker:'griswald', text:'Your first grunge track felt like you were testing the water.' },
    { speaker:'player', text:'Yeah I think I was.' },
    { speaker:'griswald', text:'This one didnt.' },
    { speaker:'player', text:'What did it feel like?' },
    { speaker:'griswald', text:'Like you knew how deep it was.' },
    { speaker:'griswald', text:'And didnt step back.' },
    { speaker:'griswald', text:'(Gift Received: Polaroid Photograph)' },
    { speaker:'player', text:'You took this?' },
    { speaker:'griswald', text:'Yeah.' },
    { speaker:'player', text:'Its just trees.' },
    { speaker:'griswald', text:'Thats where I played your track.' },
    { speaker:'griswald', text:'Sounded right out there.' },
    { speaker:'player', text:'You brought a speaker into the woods?' },
    { speaker:'griswald', text:'Obviously.' },
    { speaker:'griswald', text:'(Small pause.)' },
    { speaker:'griswald', text:'Keep it somewhere youll see it.' },
    { speaker:'player', text:'Why?' },
    { speaker:'griswald', text:'So you remember how it felt before it was number one.' },
    { speaker:'griswald', text:'Whatever stage you stand on at the end of the year' },
    { speaker:'griswald', text:'Dont make it lighter just because people are watching.' },
  ],
};

export default griswald;
