// MC Munch visual novel script
// Each level is an array of entries: either {speaker, text} or {type:'choice', speaker, options, responses}
const mcmunch = {
  1: [
    { speaker:'mcmunch', text:"Hold up. That hip-hop track '{{snap.songName}}' was YOU?" },
    { speaker:'player', text:"Yeah?" },
    { speaker:'mcmunch', text:"Bold move." },
    { speaker:'player', text:"Why?" },
    { speaker:'mcmunch', text:"Thats my lane." },
    { speaker:'player', text:"Oh. Sorry?" },
    { speaker:'mcmunch', text:"Relax. Im kidding." },
    { speaker:'mcmunch', text:"Mostly." },
    { speaker:'mcmunch', text:"You ride a beat okay." },
    { speaker:'mcmunch', text:"But your second verse? You flinched." },
    { speaker:'player', text:"Flinched?" },
    { speaker:'mcmunch', text:"Yeah. Like you didnt trust your own line." },
    { speaker:'mcmunch', text:"If youre gonna compete with me, at least swing all the way." },
  ],
  2: [
    { speaker:'mcmunch', text:'Twenty fans already?' },
    { speaker:'mcmunch', text:'Okayyy. I see you.' },
    { speaker:'player', text:'That sounded sarcastic.' },
    { speaker:'mcmunch', text:'It wasnt. Mostly.' },
    { speaker:'mcmunch', text:'Your deliverys getting better.' },
    { speaker:'player', text:'You think?' },
    { speaker:'mcmunch', text:'Yeah. But you rush the first bar when youre nervous.' },
    { speaker:'player', text:'I do not.' },
    { speaker:'mcmunch', text:'You absolutely do.' },
    { speaker:'mcmunch', text:"(Gift Received: Munchs Warm-Up Tape)" },
    { speaker:'player', text:'You sent me vocal exercises?' },
    { speaker:'mcmunch', text:'Dont look at me like that. Pros warm up.' },
    { speaker:'player', text:'Did you record this?' },
    { speaker:'mcmunch', text:'Obviously. Who else hits those notes?' },
    { speaker:'mcmunch', text:'Youve got power.' },
    { speaker:'mcmunch', text:"Just gotta stop pretending you dont." },
  ],
  3: [
    { speaker:'mcmunch', text:'Alright. Ill say it once.' },
    { speaker:'player', text:'Say what?' },
    { speaker:'mcmunch', text:'{{snap.songName}}. Fire.' },
    { speaker:'player', text:'You dont have to' },
    { speaker:'mcmunch', text:'No, I do. Because now its interesting.' },
    { speaker:'player', text:'What is?' },
    { speaker:'mcmunch', text:'Youre actually getting good.' },
    { speaker:'mcmunch', text:'Dont get comfortable though. Im still better.' },
  ],
  4: [
    { speaker:'mcmunch', text:'Top five.' },
    { speaker:'player', text:'Yeah.' },
    { speaker:'mcmunch', text:'You know what I liked?' },
    { speaker:'player', text:'What?' },
    { speaker:'mcmunch', text:'You didnt wait for the beat to carry you.' },
    { speaker:'mcmunch', text:'You stepped into it.' },
    { speaker:'mcmunch', text:'(Gift Received: Spotlight Snap Effect)' },
    { speaker:'player', text:'Whats this?' },
    { speaker:'mcmunch', text:'Stage tweak.' },
    { speaker:'player', text:'Thats vague.' },
    { speaker:'mcmunch', text:'When you perform next time, dont fade in.' },
    { speaker:'mcmunch', text:'Take the light like its yours.' },
  ],
  5: [ { speaker:'mcmunch', text:'Own the room.' } ],
  5: [
    { speaker:'mcmunch', text:'{{snap.songName}}. Number one.' },
    { speaker:'mcmunch', text:'Okay. Ill say it.' },
    { speaker:'player', text:'Say what?' },
    { speaker:'mcmunch', text:"You dont sound like youre trying to beat me anymore." },
    { speaker:'player', text:'Is that good?' },
    { speaker:'mcmunch', text:'Yeah.' },
    { speaker:'mcmunch', text:'Now you sound like you.' },
    { speaker:'mcmunch', text:'(Gift Received: Custom Vinyl Sleeve)' },
    { speaker:'mcmunch', text:'Whatever stage you end up on this year' },
    { speaker:'mcmunch', text:'Dont shrink your voice just because someone louder walks in.' },
  ],
};

export default mcmunch;
